### ISSUE TITLE
Should it be Break here? vku_framework.hpp:init function

### ISSUE THREAD

**Issue by zhenqinshang** [andy-thomason/Vookoo#11]
for (uint32_t qi = 0; qi != qprops.size(); ++qi) {
      auto &qprop = qprops[qi];
      VkBool32 presentSupport = false;
      if (pd.getSurfaceSupportKHR(qi, surface_)) {
        presentQueueFamily_ = qi;
        found = true;
		break;//here add break
      }
    }

**Comment by andy-thomason** [comment]
It could indeed. I think the logic used to be more complex which precluded the break. It would only save a microsecond or so from startup time. I'll look at this.

**Comment by zhenqinshang** [comment]
Thanks.
Closed.
