### ISSUE TITLE
Multisampling option

### ISSUE THREAD

**Issue by Carandiru0** [andy-thomason/Vookoo#14]
I was wondering if vku could support multisampling as an option to enable.
I was thinking of modifying the vku frame work and following the vulkan tutorial for multisampling. However, it is proving to be rather difficult finding all the necessary interfaces in vku / framework.
Perhaps there is a simpler way?

**Comment by andy-thomason** [comment]
Hi Jason,

I've been trying to migrate the mechanics of the framework into their own
"maker" classes so you can do more complex things
such as multisampling or rendering to PNG with only a few lines of code.

From what I remember, multisampling requires a larger buffer which is then
resolved into the final image.

The framework was originally intended as a quick and dirty "get you
started" thing, but has become something
in its own rights.

I'll try to accelerate the unbundling of the framework into makers and
queue getters.

Andy.

**Comment by isaboll1** [comment]
Will the unbundling of the framework also apply to some things within the window class? it would be useful if, for example, a person could recreate the swapchain through the window class to handle resizing, or if swapchain was it's own method that you could call, where you can pass an existing swapchain to recreate.
