### ISSUE TITLE
CMake error: target dependency added via `target_include_directories`

### ISSUE THREAD

**Issue by Robert42** [andy-thomason/Vookoo#16]
In the [example's cmake file](https://github.com/andy-thomason/Vookoo/blob/master/examples/CMakeLists.txt#L42), there's a line

    target_include_directories(${order}-${exname} PRIVATE Vulkan::Vulkan)

To my knowledge, `target_include_directories` only allows directory paths and not targets as arguments. I needed to move the `Vulkan::Vulkan` dependency to `target_link_libraries` in order to be able to compile the samples

**Comment by lhog** [comment]
Please confirm you can't compile it now (because I can) and provide your system specs: CMake version, OS, Vulkan SDK version, etc.

**Comment by 9prady9** [comment]
CMake import targets are meant to be used with `target_link_libraries` unless newer versions added support for using them `target_include_directories`. `Vulkan::Vulkan` passed to link libraries call should include the header location just as fine.

**Comment by lhog** [comment]
See if https://github.com/andy-thomason/Vookoo/pull/18 good enough

**Comment by andy-thomason** [comment]
Let me know how you get on with the merge...

**Comment by FunMiles** [comment]
The offending line has been removed in the PR for #21. If it does resolve the issue completely, then this issue should be closed.

**Comment by FunMiles** [comment]
Now that the PR for #21 has been merged, I think this issue is also addressed. @Robert42, have you tried it ?

**Comment by FunMiles** [comment]
Without further comment on this issue, should it be closed? @Robert42 can reopen it if there's still an issue for him.

**Comment by lhog** [comment]
Reopen, in case the issue persists
