### ISSUE TITLE
Vookoo example in Windows not running 

### ISSUE THREAD

**Issue by ghost** [andy-thomason/Vookoo#2]
I tried to run Vookoo in my Visual Studio, but getting this error. I used default example of Vookoo. It compiling but not running. 
![2017-08-12](https://user-images.githubusercontent.com/28119043/29234911-1b352644-7f2d-11e7-8ec2-98f1a849005d.png)

**Comment by andy-thomason** [comment]
This is most likely because the driver is not installed.

Try running vulkaninfo. If it does not run, the driver needs some attention.
