### ISSUE TITLE
Update to latest Vulkan headers

### ISSUE THREAD

**Issue by Ristovski** [andy-thomason/Vookoo#5]
The bundled `external/vulkan` headers are 10 months old now, and Vookoo doesn't seem to be updated to use more recent ones.
Attempting to use Vookoo with the latest Vulkan headers fails, for example:

```
../include/vku/vku.hpp:1190:47: error: could not convert ‘vk::Device::allocateDescriptorSetsUnique(const vk::DescriptorSetAllocateInfo&) const [with Allocator = std::allocator<vk::DescriptorSet>; typename vk::ResultValueType<std::vector<vk::UniqueHandle<vk::DescriptorSet>, Allocator> >::type = std::vector<vk::UniqueHandle<vk::DescriptorSet>, std::allocator<vk::DescriptorSet> >](dsai)’
from ‘vector<[...],allocator<vk::DescriptorSet>>’ to ‘vector<[...],allocator<vk::UniqueHandle<vk::DescriptorSet>>>’
     return device.allocateDescriptorSetsUnique(dsai);
``` 

Are there any plans on updating to the latest Vulkan version?
PS: Vulkan-Hpp also seems to be a couple of versions behind, but since it generates its own vulkan.hpp with a tool, one can just provide a newer vk.xml.

**Comment by andy-thomason** [comment]
I'll take a look at this. Any use case examples would be welcome.

**Comment by ignus2** [comment]
Any update on this? Is Vookoo considered abandoned?

**Comment by andy-thomason** [comment]
Hi Balázs,

I am focusing on bioinformatics projects at the moment and it is unlikely
that I'll restart Vookoo in the near future.

I was hoping that the NVidia team would adopt the method for the official
C++ library.

Andy.

**Comment by L2NE-dev** [comment]
I do modifying Vookoo for our project...

**Comment by andy-thomason** [comment]
I will try to do an update in the coming weeks.

If anyone would like to contribute, just drop me a line.

Andy.

**Comment by andy-thomason** [comment]
Closing this. As it is now updated.
