### ISSUE TITLE
using Vulkan-Hpp update to 1.1.85 miss  vk::SurfaceKHRDeleter change

### ISSUE THREAD

**Issue by paolobia** [andy-thomason/Vookoo#9]
I use Vulkan-Hpp update to 1.1.85
in vku_framework.hpp at 294
I have change from 
`surface_ = vk::UniqueSurfaceKHR(surface, vk::SurfaceKHRDeleter{ instance }););`
to
`surface_ = vk::UniqueSurfaceKHR(surface, vk::ObjectDestroy<vk::Instance,
                                                        vk::DispatchLoaderStatic>(instance));`

otherwise, erasing the surface_ will cause a crash

**Comment by andy-thomason** [comment]
Thanks for the update. I noticed the surface issue. Your solution is probably better than mine (making the surface a non-deleting object).

I'm not used to having people so attentive to updates!

Andy.

**Comment by andy-thomason** [comment]
If you would prefer your change, reopen this issue.
